Feature/filemanagement
ri-bulatao/iPhiTech-Backend pull request #94
Opened 2022-09-02 03:29 UTC by bestworks221

## Description

## Types of Changes

- [ ] New Menu
- [ ] Migration
- [ ] Seeder
- [ ] Controller
- [ ] Models
- [ ] Vue Pages

2022-09-02 07:55 UTC, devmode2022 requested changes

2022-09-02 07:55 UTC, devmode2022 commented on resources/js/pages/admin/file-management/List.vue
> +                        </router-link>
please use ip-button component

2022-09-02 07:55 UTC, devmode2022 commented on resources/js/pages/admin/file-management/List.vue
> +    },
Remove unused methods

2022-09-07 09:53 UTC, ri-bulatao requested changes
Please Check my Comments

2022-09-07 09:53 UTC, ri-bulatao commented on resources/js/pages/admin/file-management/Upload.vue
> +    created(){
Remove Unused Codes

2022-09-07 09:53 UTC, ri-bulatao commented on app/Http/Controllers/FileManagement/FileManagementController.php
> +            return $this->result->success($ids, __('messages.file_delete_all'));
```
$files = FileManagement::whereIn('id', $request->ids)->delete();
        if ($files) {
            return $this->result->success($files, __('messages.file_delete_all'));
```

2022-09-07 09:53 UTC, ri-bulatao commented on app/Http/Controllers/FileManagement/FileManagementController.php
> +        return $this->result->custom(false, $files_not_uploaded, __('messages.file_type_validation_error'), 200);
Should Also Show the Files That were Uploaded, I think a list would be good

2022-09-07 09:53 UTC, ri-bulatao commented on app/Http/Controllers/FileManagement/FileManagementController.php
> +        ];
Aren't the 2 Variables above have no use? Just assign the Return data to blank if needed

2022-09-07 09:53 UTC, ri-bulatao commented on resources/js/pages/admin/file-management/List.vue
> +                <div class="col-sm-12" v-if="files.length > 0">
Replace `v-if="files.length > 0"` to `v-if="files"`

2022-09-07 09:53 UTC, ri-bulatao commented on resources/js/pages/admin/file-management/List.vue
> +                                <tr v-for="(file, key) in files">
add ID on For

2022-09-07 09:53 UTC, ri-bulatao commented on resources/js/pages/admin/file-management/List.vue
> +            }
Update this function to this one:

`this.isCheckAll = this.tempFiles.length == this.files.length`

2022-09-08 05:54 UTC, bestworks221 commented on app/Http/Controllers/FileManagement/FileManagementController.php
> +        return $this->result->custom(false, $files_not_uploaded, __('messages.file_type_validation_error'), 200);
Yes, on success response it will return a list of uploaded files

2022-09-08 05:57 UTC, bestworks221 commented on app/Http/Controllers/FileManagement/FileManagementController.php
> +        ];
At that time it was just preparation of function for the integration of cloud storage.

2022-09-08 05:57 UTC, bestworks221 commented on resources/js/pages/admin/file-management/List.vue
> +                        </router-link>
updated to ip-button

2022-09-08 05:58 UTC, bestworks221 commented on resources/js/pages/admin/file-management/List.vue
> +    },
removed unused methods

2022-09-08 05:58 UTC, bestworks221 commented on resources/js/pages/admin/file-management/Upload.vue
> +    created(){
removed unused codes

2022-09-08 05:58 UTC, bestworks221 commented on app/Http/Controllers/FileManagement/FileManagementController.php
> +            return $this->result->success($ids, __('messages.file_delete_all'));
updated code

2022-09-08 05:58 UTC, bestworks221 commented on app/Http/Controllers/FileManagement/FileManagementController.php
> +        ];
updated function

2022-09-08 05:59 UTC, bestworks221 commented on resources/js/pages/admin/file-management/List.vue
> +                <div class="col-sm-12" v-if="files.length > 0">
updated code

2022-09-08 06:58 UTC, devmode2022 requested changes

2022-09-08 06:58 UTC, devmode2022 commented on resources/js/pages/handbook/index.vue
> +                console.log(payload)
Remove console.log

2022-09-08 07:25 UTC, devmode2022 approved these changes
LGTM!

2022-09-08 08:00 UTC, devmode2022 approved these changes

2022-09-08 09:07 UTC, ri-bulatao approved these changes
LGTM!

2022-09-08 09:07 UTC, merged